-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 13:09:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema centreFormation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centreFormation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centreFormation` DEFAULT CHARACTER SET utf8 ;
USE `centreFormation` ;

-- -----------------------------------------------------
-- Table `centreFormation`.`Etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`Etudiants` (
  `NumCINEtu` INT NOT NULL AUTO_INCREMENT,
  `NomEtu` VARCHAR(45) NULL,
  `PrenomEtud` VARCHAR(45) NULL,
  `dateNaissance` DATETIME NULL,
  `adressEtu` VARCHAR(45) NULL,
  `villeEtu` VARCHAR(45) NULL,
  `niveauEtu` VARCHAR(45) NULL,
  PRIMARY KEY (`NumCINEtu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`formation` (
  `codeForm` INT NOT NULL AUTO_INCREMENT,
  `titreForm` VARCHAR(45) NULL,
  `dureeForm` TIME NULL,
  `prixForm` DECIMAL(65) NULL,
  PRIMARY KEY (`codeForm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`session` (
  `codeSess` INT NOT NULL AUTO_INCREMENT,
  `nomSess` VARCHAR(45) NOT NULL,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  `formation_codeForm` INT NOT NULL,
  PRIMARY KEY (`codeSess`, `formation_codeForm`),
  INDEX `fk_session_formation1_idx` (`formation_codeForm` ASC) VISIBLE,
  CONSTRAINT `fk_session_formation1`
    FOREIGN KEY (`formation_codeForm`)
    REFERENCES `centreFormation`.`formation` (`codeForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`specialite` (
  `codeSpec` INT NOT NULL AUTO_INCREMENT,
  `nomSpec` VARCHAR(45) NULL,
  `descSpec` VARCHAR(45) NULL,
  `Active` VARCHAR(45) NULL,
  PRIMARY KEY (`codeSpec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`inscription` (
  `Etudiants_NumCINEtu` INT NOT NULL,
  `session_codeSess` INT NOT NULL,
  `typeCours` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Etudiants_NumCINEtu`, `session_codeSess`),
  INDEX `fk_Etudiants_has_session_session1_idx` (`session_codeSess` ASC) VISIBLE,
  INDEX `fk_Etudiants_has_session_Etudiants_idx` (`Etudiants_NumCINEtu` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiants_has_session_Etudiants`
    FOREIGN KEY (`Etudiants_NumCINEtu`)
    REFERENCES `centreFormation`.`Etudiants` (`NumCINEtu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiants_has_session_session1`
    FOREIGN KEY (`session_codeSess`)
    REFERENCES `centreFormation`.`session` (`codeSess`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centreFormation`.`combinaison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centreFormation`.`combinaison` (
  `specialite_codeSpec` INT NOT NULL,
  `formation_codeForm` INT NOT NULL,
  PRIMARY KEY (`specialite_codeSpec`, `formation_codeForm`),
  INDEX `fk_specialite_has_formation_formation1_idx` (`formation_codeForm` ASC) VISIBLE,
  INDEX `fk_specialite_has_formation_specialite1_idx` (`specialite_codeSpec` ASC) VISIBLE,
  CONSTRAINT `fk_specialite_has_formation_specialite1`
    FOREIGN KEY (`specialite_codeSpec`)
    REFERENCES `centreFormation`.`specialite` (`codeSpec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_specialite_has_formation_formation1`
    FOREIGN KEY (`formation_codeForm`)
    REFERENCES `centreFormation`.`formation` (`codeForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

